### Part 1: Naive Bayes Classification

In [2]:
import numpy as np
import pandas as pd
import time

from datasets import load_dataset
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

Load AG News Dataset

In [3]:
dataset = load_dataset("ag_news")

train_texts = dataset["train"]["text"]
train_labels = dataset["train"]["label"]

test_texts = dataset["test"]["text"]
test_labels = dataset["test"]["label"]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/18.6M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/120000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/7600 [00:00<?, ? examples/s]

Binary Bag of Words

In [4]:
vectorizer_bin = CountVectorizer(binary=True)

X_train_bin = vectorizer_bin.fit_transform(train_texts)
X_test_bin = vectorizer_bin.transform(test_texts)

model_bin = BernoulliNB()
start = time.time()
model_bin.fit(X_train_bin, train_labels)
training_time_bin = time.time() - start

pred_bin = model_bin.predict(X_test_bin)
accuracy_bin = accuracy_score(test_labels, pred_bin)
f1_bin = f1_score(test_labels, pred_bin, average="macro")

Term Frequency

In [5]:
vectorizer_tf = CountVectorizer(stop_words="english")

X_train_tf = vectorizer_tf.fit_transform(train_texts)
X_test_tf = vectorizer_tf.transform(test_texts)

model_tf = MultinomialNB()

start = time.time()
model_tf.fit(X_train_tf, train_labels)
training_time_tf = time.time() - start

pred_tf = model_tf.predict(X_test_tf)

acc_tf = accuracy_score(test_labels, pred_tf)
f1_tf = f1_score(test_labels, pred_tf, average="macro")

TF-IDF

In [6]:
vectorizer_tfidf = TfidfVectorizer(stop_words="english")

X_train_tfidf = vectorizer_tfidf.fit_transform(train_texts)
X_test_tfidf = vectorizer_tfidf.transform(test_texts)

model_tfidf = MultinomialNB()

start = time.time()
model_tfidf.fit(X_train_tfidf, train_labels)
training_time_tfidf = time.time() - start

pred_tfidf = model_tfidf.predict(X_test_tfidf)

acc_tfidf = accuracy_score(test_labels, pred_tfidf)
f1_tfidf = f1_score(test_labels, pred_tfidf, average="macro")

Result Table

In [7]:
results = pd.DataFrame({
    "Representation": ["Binary BoW", "TF", "TF-IDF"],
    "Accuracy": [accuracy_bin, acc_tf, acc_tfidf],
    "F1": [f1_bin, f1_tf, f1_tfidf],
    "Training Time": [training_time_bin, training_time_tf, training_time_tfidf]
})

print(results)

  Representation  Accuracy        F1  Training Time
0     Binary BoW  0.895658  0.895339       1.685681
1             TF  0.904474  0.904172       1.124140
2         TF-IDF  0.904605  0.904344       3.509139

###Dataset
D1: machine learning is fun
D2: machine learning is powerful
D3: deep learning is fun
D4: deep learning powers modern ai

In [8]:
texts = [
    "machine learning is fun",
    "machine learning is powerful",
    "deep learning is fun",
    "deep learning powers modern ai"
]

# Let’s create 2 classes manually

labels = [0, 0, 1, 1]

In [9]:
import time
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, f1_score

Binary BoW

In [10]:
vectorizer_bin = CountVectorizer(binary=True)

X_bin = vectorizer_bin.fit_transform(texts)

model_bin = BernoulliNB()

start = time.time()
model_bin.fit(X_bin, labels)
training_time_bin = time.time() - start

pred_bin = model_bin.predict(X_bin)

acc_bin = accuracy_score(labels, pred_bin)
f1_bin = f1_score(labels, pred_bin, average='macro')

Term Frequency

In [11]:
vectorizer_tf = CountVectorizer()

X_tf = vectorizer_tf.fit_transform(texts)

model_tf = MultinomialNB()

start = time.time()
model_tf.fit(X_tf, labels)
training_time_tf = time.time() - start

pred_tf = model_tf.predict(X_tf)

acc_tf = accuracy_score(labels, pred_tf)
f1_tf = f1_score(labels, pred_tf, average='macro')

TF-IDF

In [12]:
vectorizer_tfidf = TfidfVectorizer()

X_tfidf = vectorizer_tfidf.fit_transform(texts)

model_tfidf = MultinomialNB()

start = time.time()
model_tfidf.fit(X_tfidf, labels)
training_time_tfidf = time.time() - start

pred_tfidf = model_tfidf.predict(X_tfidf)

acc_tfidf = accuracy_score(labels, pred_tfidf)
f1_tfidf = f1_score(labels, pred_tfidf, average='macro')

In [13]:
results = pd.DataFrame({
    "Representation": ["Binary BoW", "TF", "TF-IDF"],
    "Accuracy": [acc_bin, acc_tf, acc_tfidf],
    "Macro F1": [f1_bin, f1_tf, f1_tfidf],
    "Training Time (seconds)": [training_time_bin, training_time_tf, training_time_tfidf]
})

results

  Representation  Accuracy  Macro F1  Training Time (seconds)
0     Binary BoW       1.0       1.0                 0.002106
1             TF       1.0       1.0                 0.001722
2         TF-IDF       1.0       1.0                 0.001413

### Part 2: Topic Modeling

In [14]:
!pip install datasets gensim

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.24.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.1.4)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.24.0->datasets) (0.24.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets) (0.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 81.4 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [15]:
import numpy as np
import pandas as pd

from datasets import load_dataset
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation


import gensim
from gensim.models import CoherenceModel
from gensim.corpora import Dictionary

Load AG News

In [16]:
dataset = load_dataset("ag_news")

texts = dataset['train']['text']

Preprocessing

In [17]:
vectorizer = CountVectorizer(
    stop_words="english",
    max_df=0.95,
    min_df=5
)

X = vectorizer.fit_transform(texts)

features_names = vectorizer.get_feature_names_out()

Function to Train LDA

In [18]:
def train_lda(n_topics):
  lda = LatentDirichletAllocation(
      n_components=n_topics,
      random_state=42,
      learning_method="batch"
  )

  lda.fit(X)
  perplexity = lda.perplexity(X)

  return lda, perplexity

Extract Top Words Per Topic

In [19]:
def get_top_words(model, n_top_words=10):
  topics = []
  for topic_idx, topic in enumerate(model.components_):
    top_words = [features_names[i]
                 for i in topic.argsort()[:-n_top_words -1:-1]]
    topics.append(top_words)
    return topics

In [20]:
tokenized_texts = [text.lower().split() for text in texts]

dictionary = Dictionary(tokenized_texts)

corpus = [dictionary.doc2bow(text) for text in tokenized_texts]

Compute Coherence

In [21]:
def compute_coherence(topics):
  coherence_model = CoherenceModel(
      topics=topics,
      texts=tokenized_texts,
      dictionary=dictionary,
      coherence='c_v'
  )
  return coherence_model.get_coherence()

Train for 5, 10, 20 Topics

In [37]:
results = []

for k in [5, 10, 20]:
  lda_model, perplexity = train_lda(k)
  topics = get_top_words(lda_model)
  coherence = compute_coherence(topics)

  results.append([k, perplexity, coherence])

Report Table

In [38]:
results_df = pd.DataFrame(
    results,
    columns=["Topics", "Perplexity", "Coherence"]
)

results_df

   Topics   Perplexity  Coherence
0       5  3714.988760   0.389173
1      10  3413.019635   0.245711
2      20  3183.409608   0.233571

In [39]:
lda_model_5, _ = train_lda(5)
topics_5 = get_top_words(lda_model_5)

for i, topic in enumerate(topics_5):
    print(f"Topic {i+1}: {topic}")

Topic 1: ['39', 'ap', 'game', 'season', 'win', 'team', 'new', 'world', 'night', 'year']

### Part 3: POS Tagging using Probabilistic Models

In [23]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [24]:
import nltk
import numpy as np
import pandas as pd
from collections import defaultdict, Counter
import math

nltk.download('treebank')
nltk.download('universal_tagset')

[nltk_data] Downloading package treebank to /root/nltk_data...
[nltk_data]   Unzipping corpora/treebank.zip.
[nltk_data] Downloading package universal_tagset to /root/nltk_data...
[nltk_data]   Unzipping taggers/universal_tagset.zip.

True

Load Penn Treebank

In [25]:
from nltk.corpus import treebank

tagged_sentences = treebank.tagged_sents(tagset='universal')

In [26]:
train_data = tagged_sentences[:3000]
test_data = tagged_sentences[3000:]

Build Baseline Model

In [27]:
word_tag_freq = defaultdict(Counter)

for sentence in train_data:
    for word, tag in sentence:
        word_tag_freq[word][tag] += 1

# Build most frequent tag dictionary
most_freq_tag = {}

for word in word_tag_freq:
    most_freq_tag[word] = word_tag_freq[word].most_common(1)[0][0]

Baseline Prediction Function

In [28]:
def baseline_predict(sentence):
    prediction = []
    for word in sentence:
        if word in most_freq_tag:
            prediction.append(most_freq_tag[word])
        else:
            prediction.append("NOUN")  # default for unseen
    return prediction

Compute Baseline Accuracy

In [29]:
correct = 0
total = 0

for sentence in test_data:
    words = [word for word, tag in sentence]
    true_tags = [tag for word, tag in sentence]

    pred_tags = baseline_predict(words)

    for t, p in zip(true_tags, pred_tags):
        if t == p:
            correct += 1
        total += 1

baseline_accuracy = correct / total
print("Baseline Accuracy:", baseline_accuracy)

Baseline Accuracy: 0.9304122598748111

Estimate HMM Parameters

In [30]:
transition_counts = defaultdict(Counter)
emission_counts = defaultdict(Counter)
tag_counts = Counter()

for sentence in train_data:
    prev_tag = "<START>"

    for word, tag in sentence:
        transition_counts[prev_tag][tag] += 1
        emission_counts[tag][word] += 1
        tag_counts[tag] += 1
        prev_tag = tag

In [31]:
tags = list(tag_counts.keys())

def transition_prob(prev_tag, curr_tag):
    return (transition_counts[prev_tag][curr_tag] + 1) / \
           (sum(transition_counts[prev_tag].values()) + len(tags))

def emission_prob(tag, word):
    return (emission_counts[tag][word] + 1) / \
           (tag_counts[tag] + len(emission_counts[tag]))

Viterbi Algorithm

In [32]:
def viterbi(sentence):
    V = [{}]
    path = {}

    # Initialization
    for tag in tags:
        V[0][tag] = math.log(transition_prob("<START>", tag)) + \
                    math.log(emission_prob(tag, sentence[0]))
        path[tag] = [tag]

    # Recursion
    for t in range(1, len(sentence)):
        V.append({})
        new_path = {}

        for curr_tag in tags:
            prob_tag = []

            for prev_tag in tags:
                prob = V[t-1][prev_tag] + \
                       math.log(transition_prob(prev_tag, curr_tag)) + \
                       math.log(emission_prob(curr_tag, sentence[t]))
                prob_tag.append((prob, prev_tag))

            best_prob, best_prev_tag = max(prob_tag)
            V[t][curr_tag] = best_prob
            new_path[curr_tag] = path[best_prev_tag] + [curr_tag]

        path = new_path

    # Termination
    final_prob, final_tag = max((V[len(sentence)-1][tag], tag) for tag in tags)

    return path[final_tag]

Evaluate HMM Accuracy

In [33]:
correct = 0
total = 0

for sentence in test_data:
    words = [word for word, tag in sentence]
    true_tags = [tag for word, tag in sentence]

    pred_tags = viterbi(words)

    for t, p in zip(true_tags, pred_tags):
        if t == p:
            correct += 1
        total += 1

hmm_accuracy = correct / total
print("HMM Accuracy:", hmm_accuracy)

HMM Accuracy: 0.8486078135117634

In [34]:
results = pd.DataFrame({
    "Model": ["Baseline", "HMM"],
    "Tagging Accuracy": [baseline_accuracy, hmm_accuracy]
})

results

      Model  Tagging Accuracy
0  Baseline          0.930412
1       HMM          0.848608